## Statistics

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/data_edited.csv", delimiter=';')
df

Start time    Completion time      Email            Q1  \
0                 NaN                NaN    RESULTS  Sonification   
1    12/8/22 11:29:21   12/8/22 12:11:53  anonymous  Sonification   
2   12/11/22 16:39:30  12/11/22 17:06:42  anonymous  Sonification   
3   12/11/22 18:13:31  12/11/22 18:30:53  anonymous  Sonification   
4   12/11/22 18:28:52  12/11/22 18:44:49  anonymous  Sonification   
5   12/11/22 18:36:17  12/11/22 19:10:36  anonymous         Music   
6   12/11/22 18:29:03  12/11/22 19:50:22  anonymous  Sonification   
7   12/11/22 21:15:40  12/11/22 21:47:19  anonymous         Music   
8   12/11/22 21:11:36  12/11/22 21:57:40  anonymous         Music   
9   12/11/22 21:49:45  12/11/22 23:08:49  anonymous         Music   
10  12/12/22 10:19:49  12/12/22 10:32:16  anonymous  Sonification   
11  12/12/22 15:59:40  12/12/22 16:34:36  anonymous         Music   
12  12/12/22 17:10:04  12/12/22 17:33:43  anonymous  Sonification   
13  12/12/22 17:43:05  12/12/22 17:58:08  anonymous  Sonification   
14  12/12/22 19:14:27  12/12/22 19:18:47  anonymous         Music   
15  12/12/22 19:40:37  12/12/22 20:03:08  anonymous  Sonification   
16  12/12/22 19:53:09  12/12/22 20:32:29  anonymous         Music   
17  12/12/22 20:09:37  12/12/22 20:45:42  anonymous  Sonification   
18  12/12/22 21:18:36  12/12/22 21:59:40  anonymous  Sonification   
19  12/13/22 18:06:31  12/13/22 18:32:55  anonymous  Sonification   
20  12/14/22 13:30:42  12/14/22 13:56:23  anonymous         Music   
21  12/14/22 23:48:29   12/15/22 0:11:37  anonymous         Music   
22  12/15/22 18:41:24  12/15/22 19:03:07  anonymous  Sonification   
23  12/15/22 19:22:58  12/15/22 19:31:53  anonymous  Sonification   
24  12/15/22 22:01:49  12/15/22 22:21:32  anonymous  Sonification   
25   12/16/22 0:47:01   12/16/22 1:14:53  anonymous         Music   
26  12/16/22 10:38:46  12/16/22 11:09:38  anonymous         Music   
27  12/16/22 13:24:21  12/16/22 13:51:45  anonymous         Music   
28   12/17/22 8:41:54  12/17/22 10:33:48  anonymous         Music   
29  12/18/22 12:12:34  12/18/22 12:30:05  anonymous         Music   
30  12/18/22 21:15:43  12/18/22 21:41:39  anonymous  Sonification   
31  12/19/22 10:26:31  12/19/22 10:43:26  anonymous         Music   
32  12/19/22 22:28:22  12/19/22 22:50:23  anonymous         Music   
33  12/20/22 18:18:31  12/20/22 18:57:19  anonymous         Music   
34  12/21/22 10:52:52  12/21/22 11:22:08  anonymous  Sonification   
35  12/19/22 17:53:32  12/21/22 17:03:43  anonymous  Sonification   
36  12/29/22 19:01:02  12/29/22 19:25:38  anonymous         Music   
37   1/15/23 19:11:48   1/15/23 19:33:04  anonymous         Music   
38   1/20/23 13:16:03   1/20/23 13:36:43  anonymous         Music   
39  12/15/22 21:13:01  12/15/22 21:14:56        ENG  Sonification   
40  12/16/22 17:46:39  12/16/22 18:06:32  anonymous  Sonification   
41   1/19/23 23:16:28    1/20/23 0:15:44  anonymous         Music   
42   1/19/23 23:18:21    1/20/23 3:34:54  anonymous         Music   
43   1/22/23 23:24:03    1/23/23 3:56:25  anonymous         Music   
44  12/15/22 21:19:13  12/15/22 21:26:25        CAT  Sonification   
45   1/18/23 17:01:54   1/18/23 17:30:51  anonymous         Music   
46   1/18/23 17:38:19   1/18/23 17:56:25  anonymous  Sonification   

              Q2            Q3            Q4             Q5            Q6  \
0          Music         Music  Sonification   Sonification         Music   
1          Music         Music         Music          Music         Music   
2   Sonification  Sonification  Sonification          Music  Sonification   
3   Sonification  Sonification  Sonification   Sonification  Sonification   
4   Sonification         Music  Sonification          Music  Sonification   
5          Music         Music         Music          Music         Music   
6   Sonification  Sonification  Sonification   Sonification  Sonification   
7          Music         Music  Sonification   Sonification         Music   
8    

In [3]:
total_responses = len(df)-1
print("Number of participants:", total_responses)

Number of participants: 46


In [4]:
df.Q1[0]#'0' index == solutions

'Sonification'

In [5]:
Q1 = len([i for i in range(len(df.Q1)) if (df.Q1[i] == df.Q1[0])])-1
Q2 = len([i for i in range(len(df.Q2)) if (df.Q2[i] == df.Q2[0])])-1
Q3 = len([i for i in range(len(df.Q3)) if (df.Q3[i] == df.Q3[0])])-1
Q4 = len([i for i in range(len(df.Q4)) if (df.Q4[i] == df.Q4[0])])-1
Q5 = len([i for i in range(len(df.Q5)) if (df.Q5[i] == df.Q5[0])])-1
Q6 = len([i for i in range(len(df.Q6)) if (df.Q6[i] == df.Q6[0])])-1
Q7 = len([i for i in range(len(df.Q7)) if (df.Q7[i] == df.Q7[0])])-1
Q8 = len([i for i in range(len(df.Q8)) if (df.Q8[i] == df.Q8[0])])-1
Q9 = len([i for i in range(len(df.Q9)) if (df.Q9[i] == df.Q9[0])])-1
Q10 = len([i for i in range(len(df.Q10)) if (df.Q10[i] == df.Q10[0])])-1
Q11 = len([i for i in range(len(df.Q11)) if (df.Q11[i] == df.Q11[0])])-1
Q12 = len([i for i in range(len(df.Q12)) if (df.Q12[i] == df.Q12[0])])-1
Q13 = len([i for i in range(len(df.Q13)) if (df.Q13[i] == df.Q13[0])])-1
Q14 = len([i for i in range(len(df.Q14)) if (df.Q14[i] == df.Q14[0])])-1
Q15 = len([i for i in range(len(df.Q15)) if (df.Q15[i] == df.Q15[0])])-1
Q16 = len([i for i in range(len(df.Q16)) if (df.Q16[i] == df.Q16[0])])-1
Q17 = len([i for i in range(len(df.Q17)) if (df.Q17[i] == df.Q17[0])])-1
Q18 = len([i for i in range(len(df.Q18)) if (df.Q18[i] == df.Q18[0])])-1
Q19 = len([i for i in range(len(df.Q19)) if (df.Q19[i] == df.Q19[0])])-1
Q20 = len([i for i in range(len(df.Q20)) if (df.Q20[i] == df.Q20[0])])-1

In [6]:
Q1#correct responses to question 1

22

In [7]:
correct = [Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20]
correct

[22, 23, 20, 35, 25, 11, 6, 36, 36, 14, 30, 22, 35, 20, 20, 20, 31, 23, 24, 17]

In [8]:
correct = np.array(correct, int)

## Correct answers mean and median

In [9]:
mean = np.mean(correct)
median = np.median(correct)
print("Correct answers mean in %:", mean/total_responses)
print("Correct answers median:", median)

Correct answers mean in %: 0.5108695652173914
Correct answers median: 22.5


In [10]:
import astropy
from astropy import stats

In [11]:
conf = astropy.stats.binom_conf_interval(correct[0], total_responses, confidence_level=0.68269, interval='jeffreys')
conf# confidence interval by question

array([0.40586689, 0.55158777])

In [12]:
success = np.sum(correct)
success

470

In [13]:
attempts = 20*total_responses
attempts

920

## Correct answers confidence interval

In [14]:
total_conf = astropy.stats.binom_conf_interval(success, attempts, confidence_level=0.68269, interval='jeffreys')
total_conf # Correct answers interval

array([0.49438607, 0.52732944])

In [63]:
pd.Series(correct/total_responses).describe()

count    20.000000
mean      0.510870
std       0.181677
min       0.130435
25%       0.434783
50%       0.489130
75%       0.657609
max       0.782609
dtype: float64

## Sonification mean, median and confidence interval

In [15]:
correct_son = correct[:10]
correct_son

array([22, 23, 20, 35, 25, 11,  6, 36, 36, 14])

In [16]:
mean_son = np.mean(correct_son)
median_son = np.median(correct_son)
print("Sonification answers mean in %:", mean_son/total_responses)
print("Sonification answers median:", median_son)

Sonification answers mean in %: 0.4956521739130435
Sonification answers median: 22.5


In [17]:
success_son = np.sum(correct_son)
attempts_son = 10* total_responses
conf_son = astropy.stats.binom_conf_interval(success_son, attempts_son, confidence_level=0.68269, interval='jeffreys')
conf_son # Correct answers interval

array([0.47237516, 0.51894807])

## Musification mean, median and confidence interval

In [18]:
correct_mus = correct[10:]
correct_mus

array([30, 22, 35, 20, 20, 20, 31, 23, 24, 17])

In [19]:
mean_mus = np.mean(correct_mus)
median_mus = np.median(correct_mus)
print("Musification answers mean in %:", mean_mus/total_responses)
print("Musification answers median:", median_mus)

Musification answers mean in %: 0.5260869565217391
Musification answers median: 22.5


In [20]:
success_mus = np.sum(correct_mus)
attempts_mus = 10* total_responses
conf_mus = astropy.stats.binom_conf_interval(success_mus, attempts_mus, confidence_level=0.68269, interval='jeffreys')
conf_mus # Correct answers interval

array([0.50277466, 0.54928598])

## Turing. Standard deviation

In [21]:
std = np.std(correct/20, dtype= np.float64)
std

0.4072775466435634

## Astronomers

In [22]:
data = df

In [23]:
astro_list = []
astro_index = []
astro_counter = 0
for j in range(len(data)):
    if ((data.Q21[j] == "Astronomer") and (data.Q31[j] != "Musician")):
        astro_counter += 1
        current_row = data.iloc[j]
        astro_list.append(current_row)
        astro_index.append(j)
        
print("Number of Astronomers:", astro_counter)
astro_df = pd.DataFrame(astro_list)
astro_df

Number of Astronomers: 4


Start time    Completion time      Email            Q1  \
35  12/19/22 17:53:32  12/21/22 17:03:43  anonymous  Sonification   
36  12/29/22 19:01:02  12/29/22 19:25:38  anonymous         Music   
38   1/20/23 13:16:03   1/20/23 13:36:43  anonymous         Music   
42   1/19/23 23:18:21    1/20/23 3:34:54  anonymous         Music   

              Q2            Q3            Q4            Q5            Q6  \
35  Sonification  Sonification  Sonification  Sonification  Sonification   
36  Sonification  Sonification  Sonification  Sonification  Sonification   
38         Music  Sonification  Sonification  Sonification  Sonification   
42         Music  Sonification  Sonification  Sonification  Sonification   

              Q7  ...             Q36     Q37  Q38  Q39  Q40  Q41   Q42  Q43  \
35  Sonification  ...   Entre 45 y 54  España  6.0  8.0  7.0  8.0   6.0  8.0   
36  Sonification  ...   Entre 35 y 44  España  7.0  7.0  7.0  8.0   8.0  6.0   
38  Sonification  ...  Entre 35 y 44   España  5.0  3.0  2.0  7.0   6.0  5.0   
42  Sonification  ...   Entre 35 y 44     USA  6.0  8.0  3.0  9.0  10.0  5.0   

    Q44  Q45  
35  6.0  6.0  
36  5.0  8.0  
38  4.0  3.0  
42  4.0  6.0  

[4 rows x 49 columns]

In [24]:
astro_total_responses = len(astro_df)

In [25]:
Q1A = len([i for i in range(len(astro_df)) if (astro_df.Q1[astro_index[i]] == data.Q1[0])])
Q2A = len([i for i in range(len(astro_df)) if (astro_df.Q2[astro_index[i]] == data.Q2[0])])
Q3A = len([i for i in range(len(astro_df)) if (astro_df.Q3[astro_index[i]] == data.Q3[0])])
Q4A = len([i for i in range(len(astro_df)) if (astro_df.Q4[astro_index[i]] == data.Q4[0])])
Q5A = len([i for i in range(len(astro_df)) if (astro_df.Q5[astro_index[i]] == data.Q5[0])])
Q6A = len([i for i in range(len(astro_df)) if (astro_df.Q6[astro_index[i]] == data.Q6[0])])
Q7A = len([i for i in range(len(astro_df)) if (astro_df.Q7[astro_index[i]] == data.Q7[0])])
Q8A = len([i for i in range(len(astro_df)) if (astro_df.Q8[astro_index[i]] == data.Q8[0])])
Q9A = len([i for i in range(len(astro_df)) if (astro_df.Q9[astro_index[i]] == data.Q9[0])])
Q10A = len([i for i in range(len(astro_df)) if (astro_df.Q10[astro_index[i]] == data.Q10[0])])
Q11A = len([i for i in range(len(astro_df)) if (astro_df.Q11[astro_index[i]] == data.Q11[0])])
Q12A = len([i for i in range(len(astro_df)) if (astro_df.Q12[astro_index[i]] == data.Q12[0])])
Q13A = len([i for i in range(len(astro_df)) if (astro_df.Q13[astro_index[i]] == data.Q13[0])])
Q14A = len([i for i in range(len(astro_df)) if (astro_df.Q14[astro_index[i]] == data.Q14[0])])
Q15A = len([i for i in range(len(astro_df)) if (astro_df.Q15[astro_index[i]] == data.Q15[0])])
Q16A = len([i for i in range(len(astro_df)) if (astro_df.Q16[astro_index[i]] == data.Q16[0])])
Q17A = len([i for i in range(len(astro_df)) if (astro_df.Q17[astro_index[i]] == data.Q17[0])])
Q18A = len([i for i in range(len(astro_df)) if (astro_df.Q18[astro_index[i]] == data.Q18[0])])
Q19A = len([i for i in range(len(astro_df)) if (astro_df.Q19[astro_index[i]] == data.Q19[0])])
Q20A = len([i for i in range(len(astro_df)) if (astro_df.Q20[astro_index[i]] == data.Q20[0])])

In [26]:
astro_correct = [Q1A,Q2A,Q3A,Q4A,Q5A,Q6A,Q7A,Q8A,Q9A,Q10A,Q11A,Q12A,Q13A,Q14A,Q15A,Q16A,Q17A,Q18A,Q19A,Q20A]
astro_correct = np.array(astro_correct, int)
astro_correct

array([1, 2, 0, 4, 4, 0, 0, 4, 3, 0, 4, 2, 3, 1, 0, 1, 3, 4, 1, 0])

In [27]:
mean_astro_correct = np.mean(astro_correct)
median_astro_correct = np.median(astro_correct)
print("Astronomers answers mean in %:", mean_astro_correct/astro_total_responses)
print("Astronmers answers median:", median_astro_correct)

Astronomers answers mean in %: 0.4625
Astronmers answers median: 1.5


In [28]:
import astropy
from astropy import stats

In [29]:
success_astro_correct = np.sum(astro_correct)
attempts_astro_correct = 20* astro_total_responses
conf_astro_correct = astropy.stats.binom_conf_interval(success_astro_correct, attempts_astro_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_astro_correct) # Correct answers interval

[0.40756586 0.51836464]


In [30]:
pd.Series(astro_correct/astro_total_responses).describe()

count    20.000000
mean      0.462500
std       0.407778
min       0.000000
25%       0.000000
50%       0.375000
75%       0.812500
max       1.000000
dtype: float64

## Musicians

In [31]:
music_list = []
music_index = []
music_counter = 0
for j in range(len(data)):
    if ((data.Q31[j] == "Musician") and (data.Q21[j] != "Astronomer")):
        music_counter += 1
        current_row = data.iloc[j]
        music_list.append(current_row)
        music_index.append(j)
        
print("Number of Musicians:", music_counter)
music_df = pd.DataFrame(music_list)
music_df

Number of Musicians: 10


Start time    Completion time      Email            Q1  \
6   12/11/22 18:29:03  12/11/22 19:50:22  anonymous  Sonification   
7   12/11/22 21:15:40  12/11/22 21:47:19  anonymous         Music   
26  12/16/22 10:38:46  12/16/22 11:09:38  anonymous         Music   
27  12/16/22 13:24:21  12/16/22 13:51:45  anonymous         Music   
30  12/18/22 21:15:43  12/18/22 21:41:39  anonymous  Sonification   
32  12/19/22 22:28:22  12/19/22 22:50:23  anonymous         Music   
41   1/19/23 23:16:28    1/20/23 0:15:44  anonymous         Music   
43   1/22/23 23:24:03    1/23/23 3:56:25  anonymous         Music   
45   1/18/23 17:01:54   1/18/23 17:30:51  anonymous         Music   
46   1/18/23 17:38:19   1/18/23 17:56:25  anonymous  Sonification   

              Q2            Q3            Q4             Q5            Q6  \
6   Sonification  Sonification  Sonification   Sonification  Sonification   
7          Music         Music  Sonification   Sonification         Music   
26         Music  Sonification         Music          Music  Sonification   
27         Music         Music         Music   Sonification  Sonification   
30  Sonification  Sonification  Sonification   Sonification  Sonification   
32         Music  Sonification  Sonification          Music  Sonification   
41         Music         Music         Music  Signification  Sonification   
43         Music         Music         Music          Music         Music   
45         Music  Sonification         Music   Sonification         Music   
46         Music  Sonification  Sonification   Sonification  Sonification   

               Q7  ...             Q36        Q37  Q38   Q39   Q40   Q41  Q42  \
6    Sonification  ...   Entre 55 y 64     España  1.0  10.0  10.0   9.0  9.0   
7    Sonification  ...   Entre 35 y 44     España  4.0   4.0   4.0   5.0  6.0   
26   Sonification  ...   Entre 25 y 34     España  6.0   7.0   7.0  10.0  9.0   
27   Sonification  ...   Entre 25 y 34     España  6.0   7.0   6.0  10.0  7.0   
30   Sonification  ...   Entre 45 y 54     España  5.0   8.0   6.0   8.0  8.0   
32   Sonification  ...   Entre 35 y 44    España   7.0   4.0   3.0   6.0  9.0   
41  Signification  ...   Entre 25 y 34  Australia  4.0   5.0   6.0   7.0  8.0   
43          Music  ...   Entre 35 y 44  Australia  6.0   5.0   8.0   8.0  8.0   
45   Sonification  ...   Entre 25 y 34     España  6.0   8.0   7.0   7.0  9.0   
46   Sonification  ...  Entre 35 y 44      España  2.0   5.0   5.0   6.0  7.0   

     Q43  Q44   Q45  
6   10.0  5.0   5.0  
7    3.0  7.0   8.0  
26   7.0  9.0  10.0  
27   8.0  5.0   5.0  
30   8.0  8.0   8.0  
32   6.0  3.0   6.0  
41   5.0  2.0   2.0  
43   8.0  6.0   7.0  
45   8.0  5.0   8.0  
46   5.0  7.0   7.0  

[10 rows x 49 columns]

In [32]:
Q1M = len([i for i in range(len(music_df)) if (music_df.Q1[music_index[i]] == data.Q1[0])])
Q2M = len([i for i in range(len(music_df)) if (music_df.Q2[music_index[i]] == data.Q2[0])])
Q3M = len([i for i in range(len(music_df)) if (music_df.Q3[music_index[i]] == data.Q3[0])])
Q4M = len([i for i in range(len(music_df)) if (music_df.Q4[music_index[i]] == data.Q4[0])])
Q5M = len([i for i in range(len(music_df)) if (music_df.Q5[music_index[i]] == data.Q5[0])])
Q6M = len([i for i in range(len(music_df)) if (music_df.Q6[music_index[i]] == data.Q6[0])])
Q7M = len([i for i in range(len(music_df)) if (music_df.Q7[music_index[i]] == data.Q7[0])])
Q8M = len([i for i in range(len(music_df)) if (music_df.Q8[music_index[i]] == data.Q8[0])])
Q9M = len([i for i in range(len(music_df)) if (music_df.Q9[music_index[i]] == data.Q9[0])])
Q10M = len([i for i in range(len(music_df)) if (music_df.Q10[music_index[i]] == data.Q10[0])])
Q11M = len([i for i in range(len(music_df)) if (music_df.Q11[music_index[i]] == data.Q11[0])])
Q12M = len([i for i in range(len(music_df)) if (music_df.Q12[music_index[i]] == data.Q12[0])])
Q13M = len([i for i in range(len(music_df)) if (music_df.Q13[music_index[i]] == data.Q13[0])])
Q14M = len([i for i in range(len(music_df)) if (music_df.Q14[music_index[i]] == data.Q14[0])])
Q15M = len([i for i in range(len(music_df)) if (music_df.Q15[music_index[i]] == data.Q15[0])])
Q16M = len([i for i in range(len(music_df)) if (music_df.Q16[music_index[i]] == data.Q16[0])])
Q17M = len([i for i in range(len(music_df)) if (music_df.Q17[music_index[i]] == data.Q17[0])])
Q18M = len([i for i in range(len(music_df)) if (music_df.Q18[music_index[i]] == data.Q18[0])])
Q19M = len([i for i in range(len(music_df)) if (music_df.Q19[music_index[i]] == data.Q19[0])])
Q20M = len([i for i in range(len(music_df)) if (music_df.Q20[music_index[i]] == data.Q20[0])])

In [33]:
music_correct = [Q1M,Q2M,Q3M,Q4M,Q5M,Q6M,Q7M,Q8M,Q9M,Q10M,Q11M,Q12M,Q13M,Q14M,Q15M,Q16M,Q17M,Q18M,Q19M,Q20M]
music_correct = np.array(music_correct, int)
music_correct

array([ 3,  8,  4,  5,  6,  3,  1,  8,  7,  6,  9,  4, 10,  3,  3,  2,  3,
        2,  4,  3])

In [34]:
music_total_responses = len(music_df)
mean_music_correct = np.mean(music_correct)
median_music_correct = np.median(music_correct)
print("musicians answers mean in %:", mean_music_correct/music_total_responses)
print("musicians answers median:", median_music_correct)

musicians answers mean in %: 0.47000000000000003
musicians answers median: 4.0


In [35]:
success_music_correct = np.sum(music_correct)
attempts_music_correct = 20* music_total_responses
conf_music_correct = astropy.stats.binom_conf_interval(success_music_correct, attempts_music_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_music_correct) # Correct answers interval


[0.43494567 0.50535343]


In [36]:
pd.Series(music_correct/music_total_responses).describe()

count    20.000000
mean      0.470000
std       0.255672
min       0.100000
25%       0.300000
50%       0.400000
75%       0.625000
max       1.000000
dtype: float64

## Experts = Astronomer&Musician


In [37]:
experts_list = []
experts_index = []
experts_counter = 0
for j in range(len(data)):
    if ((data.Q21[j] == "Astronomer") and (data.Q31[j] == "Musician")):
        experts_counter += 1
        current_row = data.iloc[j]
        experts_list.append(current_row)
        experts_index.append(j)
        
print("Number of Experts:", experts_counter)
experts_df = pd.DataFrame(experts_list)
experts_df

Number of Experts: 3


Start time    Completion time      Email            Q1  \
34  12/21/22 10:52:52  12/21/22 11:22:08  anonymous  Sonification   
39  12/15/22 21:13:01  12/15/22 21:14:56        ENG  Sonification   
44  12/15/22 21:19:13  12/15/22 21:26:25        CAT  Sonification   

              Q2     Q3            Q4            Q5            Q6  \
34  Sonification  Music  Sonification  Sonification  Sonification   
39  Sonification  Music  Sonification  Sonification         Music   
44         Music  Music  Sonification  Sonification         Music   

              Q7  ...            Q36     Q37   Q38  Q39  Q40   Q41   Q42  Q43  \
34  Sonification  ...  Entre 45 y 54  España   7.0  9.0  7.0  10.0  10.0  5.0   
39         Music  ...  Entre 35 y 44  España  10.0  9.0  6.0   9.0   9.0  8.0   
44         Music  ...  Entre 35 y 44  España   7.0  8.0  3.0   7.0   6.0  7.0   

    Q44   Q45  
34  3.0   5.0  
39  9.0  10.0  
44  8.0  10.0  

[3 rows x 49 columns]

In [38]:
Q1E = len([i for i in range(len(experts_df)) if (experts_df.Q1[experts_index[i]] == data.Q1[0])])
Q2E = len([i for i in range(len(experts_df)) if (experts_df.Q2[experts_index[i]] == data.Q2[0])])
Q3E = len([i for i in range(len(experts_df)) if (experts_df.Q3[experts_index[i]] == data.Q3[0])])
Q4E = len([i for i in range(len(experts_df)) if (experts_df.Q4[experts_index[i]] == data.Q4[0])])
Q5E = len([i for i in range(len(experts_df)) if (experts_df.Q5[experts_index[i]] == data.Q5[0])])
Q6E = len([i for i in range(len(experts_df)) if (experts_df.Q6[experts_index[i]] == data.Q6[0])])
Q7E = len([i for i in range(len(experts_df)) if (experts_df.Q7[experts_index[i]] == data.Q7[0])])
Q8E = len([i for i in range(len(experts_df)) if (experts_df.Q8[experts_index[i]] == data.Q8[0])])
Q9E = len([i for i in range(len(experts_df)) if (experts_df.Q9[experts_index[i]] == data.Q9[0])])
Q10E = len([i for i in range(len(experts_df)) if (experts_df.Q10[experts_index[i]] == data.Q10[0])])
Q11E = len([i for i in range(len(experts_df)) if (experts_df.Q11[experts_index[i]] == data.Q11[0])])
Q12E = len([i for i in range(len(experts_df)) if (experts_df.Q12[experts_index[i]] == data.Q12[0])])
Q13E = len([i for i in range(len(experts_df)) if (experts_df.Q13[experts_index[i]] == data.Q13[0])])
Q14E = len([i for i in range(len(experts_df)) if (experts_df.Q14[experts_index[i]] == data.Q14[0])])
Q15E = len([i for i in range(len(experts_df)) if (experts_df.Q15[experts_index[i]] == data.Q15[0])])
Q16E = len([i for i in range(len(experts_df)) if (experts_df.Q16[experts_index[i]] == data.Q16[0])])
Q17E = len([i for i in range(len(experts_df)) if (experts_df.Q17[experts_index[i]] == data.Q17[0])])
Q18E = len([i for i in range(len(experts_df)) if (experts_df.Q18[experts_index[i]] == data.Q18[0])])
Q19E = len([i for i in range(len(experts_df)) if (experts_df.Q19[experts_index[i]] == data.Q19[0])])
Q20E = len([i for i in range(len(experts_df)) if (experts_df.Q20[experts_index[i]] == data.Q20[0])])

In [39]:
experts_correct = [Q1E,Q2E,Q3E,Q4E,Q5E,Q6E,Q7E,Q8E,Q9E,Q10E,Q11E,Q12E,Q13E,Q14E,Q15E,Q16E,Q17E,Q18E,Q19E,Q20E]
experts_correct = np.array(experts_correct, int)
experts_correct

array([3, 1, 3, 3, 3, 2, 2, 2, 1, 0, 3, 2, 3, 2, 2, 1, 3, 3, 1, 2])

In [40]:
experts_total_responses = len(experts_df)
mean_experts_correct = np.mean(experts_correct)
median_experts_correct = np.median(experts_correct)
print("experts answers mean in %:", mean_experts_correct/experts_total_responses)
print("experts answers median:", median_experts_correct)

experts answers mean in %: 0.7000000000000001
experts answers median: 2.0


In [41]:
success_experts_correct = np.sum(experts_correct)
attempts_experts_correct = 20* experts_total_responses
conf_experts_correct = astropy.stats.binom_conf_interval(success_experts_correct, attempts_experts_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_experts_correct) # Correct answers interval


[0.63796509 0.75543347]


In [42]:
pd.Series(experts_correct/experts_total_responses).describe()

count    20.000000
mean      0.700000
std       0.303970
min       0.000000
25%       0.583333
50%       0.666667
75%       1.000000
max       1.000000
dtype: float64

## Non experts

In [43]:
nonexperts_list = []
nonexperts_index = []
nonexperts_counter = 0
for j in range(len(data)):
    if ((data.Q31[j] != "Musician") and (data.Q21[j] != "Astronomer") and (data.Email[j] != 'RESULTS')):
        nonexperts_counter += 1
        current_row = data.iloc[j]
        nonexperts_list.append(current_row)
        nonexperts_index.append(j)
        
print("Number of nonexperts:", nonexperts_counter)
nonexperts_df = pd.DataFrame(nonexperts_list)
nonexperts_df

Number of nonexperts: 29


Start time    Completion time      Email            Q1  \
1    12/8/22 11:29:21   12/8/22 12:11:53  anonymous  Sonification   
2   12/11/22 16:39:30  12/11/22 17:06:42  anonymous  Sonification   
3   12/11/22 18:13:31  12/11/22 18:30:53  anonymous  Sonification   
4   12/11/22 18:28:52  12/11/22 18:44:49  anonymous  Sonification   
5   12/11/22 18:36:17  12/11/22 19:10:36  anonymous         Music   
8   12/11/22 21:11:36  12/11/22 21:57:40  anonymous         Music   
9   12/11/22 21:49:45  12/11/22 23:08:49  anonymous         Music   
10  12/12/22 10:19:49  12/12/22 10:32:16  anonymous  Sonification   
11  12/12/22 15:59:40  12/12/22 16:34:36  anonymous         Music   
12  12/12/22 17:10:04  12/12/22 17:33:43  anonymous  Sonification   
13  12/12/22 17:43:05  12/12/22 17:58:08  anonymous  Sonification   
14  12/12/22 19:14:27  12/12/22 19:18:47  anonymous         Music   
15  12/12/22 19:40:37  12/12/22 20:03:08  anonymous  Sonification   
16  12/12/22 19:53:09  12/12/22 20:32:29  anonymous         Music   
17  12/12/22 20:09:37  12/12/22 20:45:42  anonymous  Sonification   
18  12/12/22 21:18:36  12/12/22 21:59:40  anonymous  Sonification   
19  12/13/22 18:06:31  12/13/22 18:32:55  anonymous  Sonification   
20  12/14/22 13:30:42  12/14/22 13:56:23  anonymous         Music   
21  12/14/22 23:48:29   12/15/22 0:11:37  anonymous         Music   
22  12/15/22 18:41:24  12/15/22 19:03:07  anonymous  Sonification   
23  12/15/22 19:22:58  12/15/22 19:31:53  anonymous  Sonification   
24  12/15/22 22:01:49  12/15/22 22:21:32  anonymous  Sonification   
25   12/16/22 0:47:01   12/16/22 1:14:53  anonymous         Music   
28   12/17/22 8:41:54  12/17/22 10:33:48  anonymous         Music   
29  12/18/22 12:12:34  12/18/22 12:30:05  anonymous         Music   
31  12/19/22 10:26:31  12/19/22 10:43:26  anonymous         Music   
33  12/20/22 18:18:31  12/20/22 18:57:19  anonymous         Music   
37   1/15/23 19:11:48   1/15/23 19:33:04  anonymous         Music   
40  12/16/22 17:46:39  12/16/22 18:06:32  anonymous  Sonification   

              Q2            Q3            Q4            Q5            Q6  \
1          Music         Music         Music         Music         Music   
2   Sonification  Sonification  Sonification         Music  Sonification   
3   Sonification  Sonification  Sonification  Sonification  Sonification   
4   Sonification         Music  Sonification         Music  Sonification   
5          Music         Music         Music         Music         Music   
8          Music         Music         Music         Music  Sonification   
9   Sonification         Music  Sonification  Sonification  Sonification   
10  Sonification  Sonification  Sonification  Sonification  Sonification   
11         Music  Sonification  Sonification         Music  Sonification   
12  Sonification  Sonification  Sonification  Sonification  Sonification   
13         Music  Sonification         Music         Music  Sonification   
14  Sonification         Music  Sonification         Music  Sonification   
15  Sonification         Music         Music  Sonification  Sonification   
16  Sonification         Music         Music  Sonification  Sonification   
17         Music  Sonification  Sonification  Sonification  Sonification   
18  Sonification  Sonification  Sonification         Music         Music   
19         Music  Sonification  Sonification  Sonification  Sonification   
20  Sonification         Music  Sonification  Sonification         Music   
21         Music  Sonification  Sonification         Music  Sonification   
22  Sonification  Sonification  Sonification  Sonification  Sonification   
23  Sonification         Music  Sonification         Music         Music   
24  Sonification         Music  Sonification         Music  Sonification   
25         Music         Music  Sonification         Music  Sonification   
28  Sonification  Sonification  Sonification  Sonification  Sonification   
29         Music  Sonification  Sonifica

In [44]:
Q1X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q1[nonexperts_index[i]] == data.Q1[0])])
Q2X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q2[nonexperts_index[i]] == data.Q2[0])])
Q3X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q3[nonexperts_index[i]] == data.Q3[0])])
Q4X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q4[nonexperts_index[i]] == data.Q4[0])])
Q5X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q5[nonexperts_index[i]] == data.Q5[0])])
Q6X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q6[nonexperts_index[i]] == data.Q6[0])])
Q7X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q7[nonexperts_index[i]] == data.Q7[0])])
Q8X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q8[nonexperts_index[i]] == data.Q8[0])])
Q9X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q9[nonexperts_index[i]] == data.Q9[0])])
Q10X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q10[nonexperts_index[i]] == data.Q10[0])])
Q11X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q11[nonexperts_index[i]] == data.Q11[0])])
Q12X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q12[nonexperts_index[i]] == data.Q12[0])])
Q13X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q13[nonexperts_index[i]] == data.Q13[0])])
Q14X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q14[nonexperts_index[i]] == data.Q14[0])])
Q15X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q15[nonexperts_index[i]] == data.Q15[0])])
Q16X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q16[nonexperts_index[i]] == data.Q16[0])])
Q17X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q17[nonexperts_index[i]] == data.Q17[0])])
Q18X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q18[nonexperts_index[i]] == data.Q18[0])])
Q19X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q19[nonexperts_index[i]] == data.Q19[0])])
Q20X = len([i for i in range(len(nonexperts_df)) if (nonexperts_df.Q20[nonexperts_index[i]] == data.Q20[0])])

In [45]:
nonexperts_correct = [Q1X,Q2X,Q3X,Q4X,Q5X,Q6X,Q7X,Q8X,Q9X,Q10X,Q11X,Q12X,Q13X,Q14X,Q15X,Q16X,Q17X,Q18X,Q19X,Q20X]
nonexperts_correct = np.array(nonexperts_correct, int)
nonexperts_correct

array([15, 12, 13, 23, 12,  6,  3, 22, 25,  8, 14, 14, 19, 14, 15, 16, 22,
       14, 18, 12])

In [46]:
nonexperts_total_responses = len(nonexperts_df)
mean_nonexperts_correct = np.mean(nonexperts_correct)
median_nonexperts_correct = np.median(nonexperts_correct)
print("nonexperts answers mean in %:", mean_nonexperts_correct/nonexperts_total_responses)
print("nonexperts answers median:", median_nonexperts_correct)

nonexperts answers mean in %: 0.5120689655172413
nonexperts answers median: 14.0


In [47]:
success_nonexperts_correct = np.sum(nonexperts_correct)
attempts_nonexperts_correct = 20* nonexperts_total_responses
conf_nonexperts_correct = astropy.stats.binom_conf_interval(success_nonexperts_correct, attempts_nonexperts_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_nonexperts_correct) # Correct answers interval


[0.49131071 0.53278565]


In [48]:
pd.Series(nonexperts_correct/nonexperts_total_responses).describe()

count    20.000000
mean      0.512069
std       0.193218
min       0.103448
25%       0.413793
50%       0.482759
75%       0.629310
max       0.862069
dtype: float64

##  BVI Meaning "From low loss of vision to Blindness"

In [49]:
bvi2_list = []
bvi2_index = []
bvi2_counter = 0
for j in range(len(data)):
    if ((data.Q32[j] == "Blind")or (data.Q32[j] == "Pérdida leve de visión con diagnostico médico") ):
        bvi2_counter += 1
        current_row = data.iloc[j]
        bvi2_list.append(current_row)
        bvi2_index.append(j)
        
print("Number of bvi2:", bvi2_counter)
bvi2_df = pd.DataFrame(bvi2_list)
bvi2_df

Number of bvi2: 17


Start time    Completion time      Email            Q1  \
1    12/8/22 11:29:21   12/8/22 12:11:53  anonymous  Sonification   
5   12/11/22 18:36:17  12/11/22 19:10:36  anonymous         Music   
6   12/11/22 18:29:03  12/11/22 19:50:22  anonymous  Sonification   
7   12/11/22 21:15:40  12/11/22 21:47:19  anonymous         Music   
9   12/11/22 21:49:45  12/11/22 23:08:49  anonymous         Music   
10  12/12/22 10:19:49  12/12/22 10:32:16  anonymous  Sonification   
11  12/12/22 15:59:40  12/12/22 16:34:36  anonymous         Music   
14  12/12/22 19:14:27  12/12/22 19:18:47  anonymous         Music   
18  12/12/22 21:18:36  12/12/22 21:59:40  anonymous  Sonification   
20  12/14/22 13:30:42  12/14/22 13:56:23  anonymous         Music   
21  12/14/22 23:48:29   12/15/22 0:11:37  anonymous         Music   
25   12/16/22 0:47:01   12/16/22 1:14:53  anonymous         Music   
27  12/16/22 13:24:21  12/16/22 13:51:45  anonymous         Music   
33  12/20/22 18:18:31  12/20/22 18:57:19  anonymous         Music   
35  12/19/22 17:53:32  12/21/22 17:03:43  anonymous  Sonification   
37   1/15/23 19:11:48   1/15/23 19:33:04  anonymous         Music   
43   1/22/23 23:24:03    1/23/23 3:56:25  anonymous         Music   

              Q2            Q3            Q4            Q5            Q6  \
1          Music         Music         Music         Music         Music   
5          Music         Music         Music         Music         Music   
6   Sonification  Sonification  Sonification  Sonification  Sonification   
7          Music         Music  Sonification  Sonification         Music   
9   Sonification         Music  Sonification  Sonification  Sonification   
10  Sonification  Sonification  Sonification  Sonification  Sonification   
11         Music  Sonification  Sonification         Music  Sonification   
14  Sonification         Music  Sonification         Music  Sonification   
18  Sonification  Sonification  Sonification         Music         Music   
20  Sonification         Music  Sonification  Sonification         Music   
21         Music  Sonification  Sonification         Music  Sonification   
25         Music         Music  Sonification         Music  Sonification   
27         Music         Music         Music  Sonification  Sonification   
33         Music  Sonification  Sonification         Music  Sonification   
35  Sonification  Sonification  Sonification  Sonification  Sonification   
37         Music         Music  Sonification         Music         Music   
43         Music         Music         Music         Music         Music   

              Q7  ...            Q36        Q37  Q38   Q39   Q40   Q41   Q42  \
1          Music  ...  Entre 45 y 54     España  7.0   9.0   6.0   8.0  10.0   
5          Music  ...  Entre 55 y 64     España  3.0   8.0   7.0   7.0   8.0   
6   Sonification  ...  Entre 55 y 64     España  1.0  10.0  10.0   9.0   9.0   
7   Sonification  ...  Entre 35 y 44     España  4.0   4.0   4.0   5.0   6.0   
9   Sonification  ...  Entre 55 y 64     España  2.0   4.0   2.0   6.0   3.0   
10  Sonification  ...  Entre 45 y 54     España  7.0   9.0   7.0   7.0   9.0   
11  Sonification  ...      Más de 65    España   8.0   8.0   8.0   8.0   8.0   
14         Music  ...  Entre 45 y 54     España  7.0   7.0   7.0   7.0   7.0   
18  Sonification  ...      Más de 65    España   4.0   7.0   7.0   6.0   3.0   
20  Sonification  ...  Entre 45 y 54    España   3.0   4.0   8.0   6.0   8.0   
21  Sonification  ...  Entre 55 y 64     España  1.0   5.0   5.0   7.0  10.0   
25  Sonification  ...      Más de 65    España   5.0   6.0   8.0   7.0   8.0   
27  Sonification  ...  Entre 25 y 34     España  6.0   7.0   6.0  10.0   7.0   
33  Sonification  ...  Entre 45 y 54     España  3.0   4.0   4.0   5.0   7.0   
35  Sonification  ...  Entre 45 y 54     España  6.0   8.0   7.0   8.0   6.0   
37  Sonification  ...  Entre 45 y 54     España  6.0   6.0   7.0   8.0   5.0   
43         Music  ...  Entre 35 y 44  A

In [50]:
Q1bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q1[bvi2_index[i]] == data.Q1[0])])
Q2bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q2[bvi2_index[i]] == data.Q2[0])])
Q3bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q3[bvi2_index[i]] == data.Q3[0])])
Q4bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q4[bvi2_index[i]] == data.Q4[0])])
Q5bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q5[bvi2_index[i]] == data.Q5[0])])
Q6bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q6[bvi2_index[i]] == data.Q6[0])])
Q7bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q7[bvi2_index[i]] == data.Q7[0])])
Q8bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q8[bvi2_index[i]] == data.Q8[0])])
Q9bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q9[bvi2_index[i]] == data.Q9[0])])
Q10bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q10[bvi2_index[i]] == data.Q10[0])])
Q11bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q11[bvi2_index[i]] == data.Q11[0])])
Q12bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q12[bvi2_index[i]] == data.Q12[0])])
Q13bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q13[bvi2_index[i]] == data.Q13[0])])
Q14bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q14[bvi2_index[i]] == data.Q14[0])])
Q15bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q15[bvi2_index[i]] == data.Q15[0])])
Q16bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q16[bvi2_index[i]] == data.Q16[0])])
Q17bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q17[bvi2_index[i]] == data.Q17[0])])
Q18bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q18[bvi2_index[i]] == data.Q18[0])])
Q19bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q19[bvi2_index[i]] == data.Q19[0])])
Q20bvi2 = len([i for i in range(len(bvi2_df)) if (bvi2_df.Q20[bvi2_index[i]] == data.Q20[0])])

In [51]:
bvi2_correct = [Q1bvi2,Q2bvi2,Q3bvi2,Q4bvi2,Q5bvi2,Q6bvi2,Q7bvi2,Q8bvi2,Q9bvi2,Q10bvi2,Q11bvi2,Q12bvi2,Q13bvi2,Q14bvi2,Q15bvi2,Q16bvi2,Q17bvi2,Q18bvi2,Q19bvi2,Q20bvi2]
bvi2_correct = np.array(bvi2_correct, int)
bvi2_correct

array([ 5, 10, 10, 13,  7,  7,  4, 12, 13,  7,  9,  9, 13,  8,  6,  8, 12,
        7, 10,  6])

In [52]:
bvi2_total_responses = len(bvi2_df)
mean_bvi2_correct = np.mean(bvi2_correct)
median_bvi2_correct = np.median(bvi2_correct)
print("bvi2 answers mean in %:", mean_bvi2_correct/bvi2_total_responses)
print("bvi2 answers median:", median_bvi2_correct)

bvi2 answers mean in %: 0.5176470588235295
bvi2 answers median: 8.5


In [53]:
success_bvi2_correct = np.sum(bvi2_correct)
attempts_bvi2_correct = 20* bvi2_total_responses
conf_bvi2_correct = astropy.stats.binom_conf_interval(success_bvi2_correct, attempts_bvi2_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_bvi2_correct) # Correct answers interval


[0.49053557 0.54465493]


In [54]:
pd.Series(bvi2_correct/bvi2_total_responses).describe()

count    20.000000
mean      0.517647
std       0.162614
min       0.235294
25%       0.411765
50%       0.500000
75%       0.617647
max       0.764706
dtype: float64

## NON BVI

In [55]:
nonbvi_list = []
nonbvi_index = []
nonbvi_counter = 0
for j in range(len(data)):
    if ((data.Q32[j] == "Ninguno")):
        nonbvi_counter += 1
        current_row = data.iloc[j]
        nonbvi_list.append(current_row)
        nonbvi_index.append(j)
        
print("Number of nonbvi:", nonbvi_counter)
nonbvi_df = pd.DataFrame(nonbvi_list)
nonbvi_df

Number of nonbvi: 29


Start time    Completion time      Email            Q1  \
2   12/11/22 16:39:30  12/11/22 17:06:42  anonymous  Sonification   
3   12/11/22 18:13:31  12/11/22 18:30:53  anonymous  Sonification   
4   12/11/22 18:28:52  12/11/22 18:44:49  anonymous  Sonification   
8   12/11/22 21:11:36  12/11/22 21:57:40  anonymous         Music   
12  12/12/22 17:10:04  12/12/22 17:33:43  anonymous  Sonification   
13  12/12/22 17:43:05  12/12/22 17:58:08  anonymous  Sonification   
15  12/12/22 19:40:37  12/12/22 20:03:08  anonymous  Sonification   
16  12/12/22 19:53:09  12/12/22 20:32:29  anonymous         Music   
17  12/12/22 20:09:37  12/12/22 20:45:42  anonymous  Sonification   
19  12/13/22 18:06:31  12/13/22 18:32:55  anonymous  Sonification   
22  12/15/22 18:41:24  12/15/22 19:03:07  anonymous  Sonification   
23  12/15/22 19:22:58  12/15/22 19:31:53  anonymous  Sonification   
24  12/15/22 22:01:49  12/15/22 22:21:32  anonymous  Sonification   
26  12/16/22 10:38:46  12/16/22 11:09:38  anonymous         Music   
28   12/17/22 8:41:54  12/17/22 10:33:48  anonymous         Music   
29  12/18/22 12:12:34  12/18/22 12:30:05  anonymous         Music   
30  12/18/22 21:15:43  12/18/22 21:41:39  anonymous  Sonification   
31  12/19/22 10:26:31  12/19/22 10:43:26  anonymous         Music   
32  12/19/22 22:28:22  12/19/22 22:50:23  anonymous         Music   
34  12/21/22 10:52:52  12/21/22 11:22:08  anonymous  Sonification   
36  12/29/22 19:01:02  12/29/22 19:25:38  anonymous         Music   
38   1/20/23 13:16:03   1/20/23 13:36:43  anonymous         Music   
39  12/15/22 21:13:01  12/15/22 21:14:56        ENG  Sonification   
40  12/16/22 17:46:39  12/16/22 18:06:32  anonymous  Sonification   
41   1/19/23 23:16:28    1/20/23 0:15:44  anonymous         Music   
42   1/19/23 23:18:21    1/20/23 3:34:54  anonymous         Music   
44  12/15/22 21:19:13  12/15/22 21:26:25        CAT  Sonification   
45   1/18/23 17:01:54   1/18/23 17:30:51  anonymous         Music   
46   1/18/23 17:38:19   1/18/23 17:56:25  anonymous  Sonification   

              Q2            Q3            Q4             Q5            Q6  \
2   Sonification  Sonification  Sonification          Music  Sonification   
3   Sonification  Sonification  Sonification   Sonification  Sonification   
4   Sonification         Music  Sonification          Music  Sonification   
8          Music         Music         Music          Music  Sonification   
12  Sonification  Sonification  Sonification   Sonification  Sonification   
13         Music  Sonification         Music          Music  Sonification   
15  Sonification         Music         Music   Sonification  Sonification   
16  Sonification         Music         Music   Sonification  Sonification   
17         Music  Sonification  Sonification   Sonification  Sonification   
19         Music  Sonification  Sonification   Sonification  Sonification   
22  Sonification  Sonification  Sonification   Sonification  Sonification   
23  Sonification         Music  Sonification          Music         Music   
24  Sonification         Music  Sonification          Music  Sonification   
26         Music  Sonification         Music          Music  Sonification   
28  Sonification  Sonification  Sonification   Sonification  Sonification   
29         Music  Sonification  Sonification          Music  Sonification   
30  Sonification  Sonification  Sonification   Sonification  Sonification   
31  Sonification  Sonification  Sonification          Music  Sonification   
32         Music  Sonification  Sonification          Music  Sonification   
34  Sonification         Music  Sonification   Sonification  Sonification   
36  Sonification  Sonification  Sonification   Sonification  Sonification   
38         Music  Sonification  Sonification   Sonification  Sonification   
39  Sonification         Music  Sonification   Sonification         Music   
40  Sonification  Sonification  Sonification   Sonification  Sonification   
41         Musi

In [57]:
Q1nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q1[nonbvi_index[i]] == data.Q1[0])])
Q2nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q2[nonbvi_index[i]] == data.Q2[0])])
Q3nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q3[nonbvi_index[i]] == data.Q3[0])])
Q4nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q4[nonbvi_index[i]] == data.Q4[0])])
Q5nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q5[nonbvi_index[i]] == data.Q5[0])])
Q6nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q6[nonbvi_index[i]] == data.Q6[0])])
Q7nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q7[nonbvi_index[i]] == data.Q7[0])])
Q8nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q8[nonbvi_index[i]] == data.Q8[0])])
Q9nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q9[nonbvi_index[i]] == data.Q9[0])])
Q10nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q10[nonbvi_index[i]] == data.Q10[0])])
Q11nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q11[nonbvi_index[i]] == data.Q11[0])])
Q12nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q12[nonbvi_index[i]] == data.Q12[0])])
Q13nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q13[nonbvi_index[i]] == data.Q13[0])])
Q14nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q14[nonbvi_index[i]] == data.Q14[0])])
Q15nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q15[nonbvi_index[i]] == data.Q15[0])])
Q16nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q16[nonbvi_index[i]] == data.Q16[0])])
Q17nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q17[nonbvi_index[i]] == data.Q17[0])])
Q18nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q18[nonbvi_index[i]] == data.Q18[0])])
Q19nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q19[nonbvi_index[i]] == data.Q19[0])])
Q20nonbvi = len([i for i in range(len(nonbvi_df)) if (nonbvi_df.Q20[nonbvi_index[i]] == data.Q20[0])])

In [58]:
nonbvi_correct = [Q1nonbvi,Q2nonbvi,Q3nonbvi,Q4nonbvi,Q5nonbvi,Q6nonbvi,Q7nonbvi,Q8nonbvi,Q9nonbvi,Q10nonbvi,Q11nonbvi,Q12nonbvi,Q13nonbvi,Q14nonbvi,Q15nonbvi,Q16nonbvi,Q17nonbvi,Q18nonbvi,Q19nonbvi,Q20nonbvi]
nonbvi_correct = np.array(nonbvi_correct, int)
nonbvi_correct

array([17, 13, 10, 22, 18,  4,  2, 24, 23,  7, 21, 13, 22, 12, 14, 12, 19,
       16, 14, 11])

In [59]:
nonbvi_total_responses = len(nonbvi_df)
mean_nonbvi_correct = np.mean(nonbvi_correct)
median_nonbvi_correct = np.median(nonbvi_correct)
print("nonbvi answers mean in %:", mean_nonbvi_correct/nonbvi_total_responses)
print("nonbvi answers median:", median_nonbvi_correct)

nonbvi answers mean in %: 0.506896551724138
nonbvi answers median: 14.0


In [61]:
success_nonbvi_correct = np.sum(nonbvi_correct)
attempts_nonbvi_correct = 20* nonbvi_total_responses
conf_nonbvi_correct = astropy.stats.binom_conf_interval(success_nonbvi_correct, attempts_nonbvi_correct, confidence_level=0.68269, interval='jeffreys')
print(conf_nonbvi_correct) # Correct answers interval


[0.48614314 0.52762621]


In [62]:
pd.Series(nonbvi_correct/nonbvi_total_responses).describe()

count    20.000000
mean      0.506897
std       0.213770
min       0.068966
25%       0.405172
50%       0.482759
75%       0.672414
max       0.827586
dtype: float64